services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=49839c72749ca2b51ca5eb2c119c67be86aeb6972653f74ac9f2dfe7d4cafb8d
      - DATABASE_URL=postgresql://postgres:a@host.docker.internal:5432/todo_app
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=a
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: